base_url="http://localhost:8080/"
redirect_allowed_domains=["*.server.lan"]

[oidc]
client_id="id-sea"
client_secret="changeme"
issuer_url="https://keycloak.lan/realms/home"

[session.cookie]
secret="changeme"

[access_control.host_groups]

admin = [ "*.server.lan" ]

tools = [
    "wiki.server.lan",
    "gitlab.server.lan"
]

media = [
    "plex.server.lan",
    "photos.server.lan"
]

[access_control.acls]
family-user = ["media"]
dev-user = ["media", "tools"]
admin-user = ["admin"]